#
# marichi - cooperative kernel for AVR (R) Mega microcontrollers
# Copyright (C) 2026  notweerdmonk
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#


# Configuration flags for build
# These can be overridden as command line variables passed to Make invocation

# Enable/disable debug build
DEBUG                                       ?= 1

# Enable/disable UART module
UART                                        ?= 1

# Enable/disable LCD module
LCD                                         ?= 1

# Enable/disable ADC module
ADC                                         ?= 1

# Enable/disable resource management
RESMGMT                                     ?= 1

# Enable/disable debugger module
DEBUGGER                                    ?= 1

# Enable/disable simulation with simavr
SIM                                         ?= 1

# Set verbosity levels of messages and logs
# Valid values are 0, 1, 2
VV                                          ?= 2
